// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwtZclLSkLT3LMIoyXczKK7d9N6_rIpS8',
    appId: '1:983304295862:ios:40551c85357585a18b9d17',
    messagingSenderId: '983304295862',
    projectId: 'budget-pal-843f5',
    storageBucket: 'budget-pal-843f5.firebasestorage.app',
    iosClientId: '983304295862-11bar4odfqds89o0k0q4ch18iqli6pm4.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetPal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTY7MGnYjo5AW3QOoQHjuN3a0oxg-zwRE',
    appId: '1:983304295862:web:7e7f1b219a4e6e568b9d17',
    messagingSenderId: '983304295862',
    projectId: 'budget-pal-843f5',
    authDomain: 'budget-pal-843f5.firebaseapp.com',
    storageBucket: 'budget-pal-843f5.firebasestorage.app',
    measurementId: 'G-ZW0ERS9GJ8',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_qJ8Zuu5KaqQkvt1bm_t85gGtfvnGVjQ',
    appId: '1:983304295862:web:7e7f1b219a4e6e568b9d17',
    messagingSenderId: '983304295862',
    projectId: 'budget-pal-843f5',
    authDomain: 'budget-pal-843f5.firebaseapp.com',
    storageBucket: 'budget-pal-843f5.firebasestorage.app',
    measurementId: 'G-ZW0ERS9GJ8',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwtZclLSkLT3LMIoyXczKK7d9N6_rIpS8',
    appId: '1:983304295862:ios:40551c85357585a18b9d17',
    messagingSenderId: '983304295862',
    projectId: 'budget-pal-843f5',
    storageBucket: 'budget-pal-843f5.firebasestorage.app',
    iosClientId: '983304295862-11bar4odfqds89o0k0q4ch18iqli6pm4.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetPal',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_qJ8Zuu5KaqQkvt1bm_t85gGtfvnGVjQ',
    appId: '1:983304295862:android:0beef77c2ca22ddb8b9d17',
    messagingSenderId: '983304295862',
    projectId: 'budget-pal-843f5',
    storageBucket: 'budget-pal-843f5.firebasestorage.app',
  );

}